### ISSUE TITLE
Password lost non funzionante

### ISSUE THREAD

**Issue by pzucchi** [madbob/GASdotto#60]
(Gasdotto SAAS)
Immettendo un indirizzo email valido nel campo password lost il sistema comunica di aver effettuato l'invio, mentre su circa 20 indirizzi email diversi nessuno ha ricevuto la mail per poter cambiare la password.

Le notifiche via email vengono inviate e ricevute correttamente.

**Comment by pzucchi** [comment]
Ci sono novità su questo problema? Faccio assistenza agli utenti e dover anche seguirli per le password perse è piuttosto seccante :(

**Comment by madbob** [comment]
Ok, forse ho trovato l'origine del problema.
Dovrebbero esserti arrivate una o due mail di reset, le ho generate io.

**Comment by pzucchi** [comment]
Confermo!
Il giorno dom 13 dic 2015 alle 16:30 Roberto Guido <notifications@github.com>
ha scritto:
