### ISSUE TITLE
spese di trasporto

### ISSUE THREAD

**Issue by danieledalma** [madbob/GASdotto#63]
sarebbe interessante avere una gestione delle spese di trasporto più semplice

inserire la spesa totale che automaticamente viene divisa per valore totale dell unità di misura    
 ( normalmente KG) e conseguentemente moltiplicata per i valori parziali dei vari utenti:
es:
utenti A  20kg
         B 15kg
         C 65 kg
totale   100  kg  spese di trasporto €20

20/100 * 20 addebitato ad A
20/100*15 addebitato a B
20/100*65 addebitato a C
non so se ho postato in modo corretto e nel posto corretto se ho fatto errori scusatemi non sono esperto di questi strumenti
daniele

**Comment by madbob** [comment]
Questa considerazione è più che ragionevole, anzi forse non è neppure la prima volta che viene mossa.
Me la sono segnata tra i miei appunti per la prossima reimplementazine.

**Comment by danieledalma** [comment]
Grazie
Daniele

2017-02-12 14:52 GMT+01:00 Roberto Guido <notifications@github.com>:

**Comment by madbob** [comment]
Aggiunto in GASdottoNG - https://github.com/madbob/GASdottoNG/
