### ISSUE TITLE
giacenza magazzino

### ISSUE THREAD

**Issue by danieledalma** [madbob/GASdotto#64]
vorrei gestire il magazzino del nostro gruppo con gasdotto,
inserisco in fornitori/prodotti la quantità massima disponibile, apro l' ordine per le consegne mensili tutto bene blocca gli ordin superano il numero massimo di prodotti disponibili, consegnamo merce e chiudiamo l ordine tutto bene
Il problema sorge quando vado ad aprire un nuovo ordine mi da nuovamente la totale disponibilità della merce anche quella già consegnata, mi tocca ogni volta reinserire le giacenze.....
grazie
Daniele gas savona

**Comment by madbob** [comment]
Non comprendo come la gestione del magazzino dovrebbe essere in carico al gruppo, teoricamente dovrebbe essere una informazione gestita dal fornitore. Il parametro sulla quantità massima ordinabile per un dato prodotto dovrebbe variare da ordine a ordine, a seconda della disponibilità comunicata di volta in volta dal fornitore.
In quali casi siete voi a gestire il magazzino? E' il gruppo stesso che funge da fornitore? Mi fai un esempio pratico?

**Comment by danieledalma** [comment]
Grazie della celere risposta;
Si teniamo una certa quantità di prodotti non deperibili ( pasta,
detersivi, riso) , dei quali facciamo ordini 1/2 volte all anno
e visto che non tutti riusciamo a programmarci le forniture a lungo termine
teniamo una scorta nel nostro magazzino, per integrare gli ordini
individuali, per far fronte ai bisogni di nuovi associati che altrimenti si
troverebbero a dover aspettare mesi prima di poter fare l ordine, per poter
fare forniture più dimensionate riducendo i trasporti delle merci.
Probabilmente è un anomalia nel settore dei GAS ma il nostro gruppo è nato
proprio sul magazzino all' inizio non esistevano gli ordini individuali si
decideva insieme cosa acquistare e poi gli associati prelevavano in base
alle proprie esigenze ed è una tradizione che ci è rimasta ed è molto
apprezzata.
ora avremmo voluto  inserire MAGAZZINO come fornitore su GASDOTTO inserire
tutte le giacenze e gli associati fanno gli ordini tramite GASDOTTO i
responsabili del magazzino preparano i prodotti che vengono consegnati alla
riunione mensile del gruppo.
spero di essermi chiarito
grazie dell' ottimo strumento che ci metti a disposizione e
a presto
Daniele

Il giorno 12 febbraio 2017 14:55, Roberto Guido <notifications@github.com>
ha scritto:

**Comment by madbob** [comment]
In effetti si, è un caso d'uso molto particolare. Me lo sono segnato tra le funzionalità future di GASdottoNG, dubito verrà introdotta già nella prima versione ma ne tengo conto.

**Comment by danieledalma** [comment]
bene , una curiosità GASdotto   NG cosa indica?
noi utilizziamo la versione sul vostro server
Daniele

2017-02-12 22:31 GMT+01:00 Roberto Guido <notifications@github.com>:

**Comment by madbob** [comment]
GASdottoNG è la reimplementazione completa di GASdotto, attualmente in fase di sviluppo
https://github.com/madbob/gasdottong
E' destinato a prendere il posto di GASdotto nei prossimi mesi.

**Comment by madbob** [comment]
Spostato tra le cose da fare in GASdottoNG.
