### ISSUE TITLE
Problemi autenticazione

### ISSUE THREAD

**Issue by MLauri** [madbob/GASdotto#65]
Buongiorno,
da ieri non è più possibile per tutti gli utenti autenticarsi all'istanza http://arnogas.gasdotto.net/GASdotto.html

Browser: chrome
Msg di errore: autenticazione fallita

Ho provato a richiedere il reset della password per un'utenza senza successo (non ho ricevuto l'email).
Grazie per il supporto

**Comment by madbob** [comment]
L'altro giorno ho operato la migrazione delle istanze su un nuovo server, per qualche motivo il vostro database era stato importato due volte generando problemi. Ora l'ho ripristinato, prova adesso e fammi sapere.

**Comment by MLauri** [comment]
Grazie mille.
Ho provato l'accesso ed il problema è risolto.
Grazie!
