### ISSUE TITLE
Inserire un nuovo prodotto di un fornitore in un ordine già aperto

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdotto#66]
Ciao.
Non credo di aver trovato la possibilità in oggetto! Ho inserito un nuovo prodotto di un fornitore a ordine già aperto! E mi piacerebbe immediatamente proporlo. Purtroppo credo non si possa fare!
E' possibile sviluppare ciò? a mio avviso particolarmente importante?
Grazie

**Comment by madbob** [comment]
Per aggiungere un prodotto ad un ordine già aperto è sufficiente cliccare il pulsante "Tutti" in alto a sinistra nella tabella dei prodotti dell'ordine (vedi immagine)

![Screenshot-20200415014821-918x888](https://user-images.githubusercontent.com/166089/79284582-5f3c6880-7ebb-11ea-9dfd-7eae66f4123b.png)

Appare l'elenco completo dei prodotti del fornitore, inclusi quelli non abilitati per l'ordine, e cliccando la spunta accanto (e poi "Salva", al fondo) è possibile attivarli e disattivarli.

Nota bene: questo progetto GitHub fa riferimento alla vecchia versione di GASdotto, non più mantenuta ed aggiornata. Il progetto nuovo lo trovi qui -> https://github.com/madbob/gasdottong/
